import SplashScreen from './splashScreen';
import Login from './login';
import Dashboard from './dashboard';
import Produk from './produk';
import DetailProduk from './produk/detail';
import Cart from './cart';
import Checkout from './checkout';
import Profile from './profile';
import ScrollableTabViewPager1 from './tabView';
import Alamat from './checkout/alamat';

export {SplashScreen};
export {Login};
export {Dashboard};
export {Produk};
export {DetailProduk};
export {Cart};
export {Checkout};
export {Profile};
export {ScrollableTabViewPager1};
export {Alamat};
